version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes: [".:/app"]
    environment:
      - DATABASE_URL=postgresql+psycopg2://app:app@db:5432/appdb
      - SECRET_KEY=CHANGE_ME_IN_PROD
      - USE_TRANSFORMERS=true
      - CHROMA_PATH=chroma_db
      - EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2
    command: bash -lc "pip install -r requirements.txt && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    ports: ["8000:8000"]
    depends_on:
      db:
        condition: service_healthy
  ui:
    image: python:3.11-slim
    working_dir: /app
    volumes: [".:/app"]
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    command: bash -lc "pip install -r requirements.txt && streamlit run frontend/app.py --server.port 8501 --server.headless true --server.address 0.0.0.0"
    ports: ["8501:8501"]
    depends_on: ["api"]
